import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../../core/theme/theme.dart';
import '../../../core/widgets/widgets.dart';
import '../../../models/protocol.dart';
import '../widgets/peptide_label_color.dart';

/// A read-only calendar generated from the user's saved protocol schedules.
///
/// The planner intentionally delegates all schedule decisions to
/// [ProtocolPeptide.scheduleForDate] so it can never drift from the dose logs
/// and reminders generated by [ProtocolProvider].
class WeeklyPlannerScreen extends StatefulWidget {
  const WeeklyPlannerScreen({
    super.key,
    required this.protocols,
    this.initialDate,
  });

  final List<Protocol> protocols;
  final DateTime? initialDate;

  @override
  State<WeeklyPlannerScreen> createState() => _WeeklyPlannerScreenState();
}

class _WeeklyPlannerScreenState extends State<WeeklyPlannerScreen> {
  late DateTime _selectedDate;
  late DateTime _weekStart;

  @override
  void initState() {
    super.initState();
    _selectedDate = _day(widget.initialDate ?? DateTime.now());
    _weekStart = _mondayOf(_selectedDate);
  }

  @override
  Widget build(BuildContext context) {
    final days = List<DateTime>.generate(
      7,
      (index) => _weekStart.add(Duration(days: index)),
    );
    final selectedItems = _itemsForDate(_selectedDate);
    final selectedWashouts = _washoutsForDate(_selectedDate);

    return Scaffold(
      backgroundColor: AppColors.background,
      body: SafeArea(
        child: Column(
          children: [
            _PlannerHeader(
              rangeLabel: _weekRangeLabel(_weekStart),
              onBack: () => Navigator.of(context).pop(),
              onPrevious: () => _moveWeek(-1),
              onNext: () => _moveWeek(1),
            ),
            Padding(
              padding: const EdgeInsets.fromLTRB(
                AppSpacing.screenHorizontal,
                AppSpacing.base,
                AppSpacing.screenHorizontal,
                AppSpacing.sm,
              ),
              child: Row(
                children: [
                  Text('SCHEDULE // 7 DAYS', style: AppTypography.systemLabel),
                  const Spacer(),
                  GestureDetector(
                    onTap: _jumpToToday,
                    child: Text(
                      'TODAY',
                      style: AppTypography.systemLabel.copyWith(
                        color: AppColors.textSecondary,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: AppSpacing.screenHorizontal,
              ),
              child: Row(
                children: [
                  for (final date in days)
                    Expanded(
                      child: _DayButton(
                        date: date,
                        doseCount: _itemsForDate(date).length,
                        selected: _sameDay(date, _selectedDate),
                        isToday: _sameDay(date, DateTime.now()),
                        onTap: () {
                          HapticFeedback.selectionClick();
                          setState(() => _selectedDate = date);
                        },
                      ),
                    ),
                ],
              ),
            ),
            const SizedBox(height: AppSpacing.lg),
            Expanded(
              child: ListView(
                padding: const EdgeInsets.fromLTRB(
                  AppSpacing.screenHorizontal,
                  0,
                  AppSpacing.screenHorizontal,
                  AppSpacing.screenBottom,
                ),
                children: [
                  Text(
                    _fullDateLabel(_selectedDate).toUpperCase(),
                    style: AppTypography.systemLabel.copyWith(
                      color: AppColors.textSecondary,
                    ),
                  ),
                  const SizedBox(height: AppSpacing.sm),
                  if (selectedItems.isEmpty && selectedWashouts.isEmpty)
                    const _EmptyDayCard()
                  else ...[
                    for (final item in selectedItems) ...[
                      _PlannedDoseCard(item: item),
                      const SizedBox(height: AppSpacing.cardGap),
                    ],
                    for (final item in selectedWashouts) ...[
                      _WashoutCard(item: item),
                      const SizedBox(height: AppSpacing.cardGap),
                    ],
                  ],
                  const SizedBox(height: AppSpacing.sm),
                  Text(
                    'Tracking only. This calendar reflects your saved protocol and does not provide dosing advice.',
                    style: AppTypography.disclaimer.copyWith(
                      color: AppColors.textSecondary,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  List<_PlannerItem> _itemsForDate(DateTime date) {
    final result = <_PlannerItem>[];
    for (final protocol in widget.protocols) {
      if (protocol.status != ProtocolStatus.active ||
          date.isBefore(_day(protocol.startDate))) {
        continue;
      }
      if (protocol.endDate != null && date.isAfter(_day(protocol.endDate!))) {
        continue;
      }
      for (var index = 0; index < protocol.peptides.length; index++) {
        final peptide = protocol.peptides[index];
        final schedule = peptide.scheduleForDate(
          protocolStart: protocol.startDate,
          date: date,
        );
        if (schedule == null) continue;
        final phase = peptide.phaseForDate(
          protocolStart: protocol.startDate,
          date: date,
        );
        for (final time in schedule.scheduledTimes) {
          result.add(
            _PlannerItem(
              protocol: protocol,
              peptide: peptide,
              schedule: schedule,
              time: time,
              phase: phase,
              colorHex: peptide.labelColorHex.isEmpty
                  ? defaultPeptideLabelColorHex(index)
                  : peptide.labelColorHex,
            ),
          );
        }
      }
    }
    result.sort((a, b) => a.time.compareTo(b.time));
    return result;
  }

  List<_WashoutItem> _washoutsForDate(DateTime date) {
    final result = <_WashoutItem>[];
    for (final protocol in widget.protocols) {
      if (protocol.status != ProtocolStatus.active) continue;
      for (var index = 0; index < protocol.peptides.length; index++) {
        final peptide = protocol.peptides[index];
        if (!peptide.isInWashout(
          protocolStart: protocol.startDate,
          date: date,
        )) {
          continue;
        }
        result.add(
          _WashoutItem(
            protocol: protocol,
            peptide: peptide,
            colorHex: peptide.labelColorHex.isEmpty
                ? defaultPeptideLabelColorHex(index)
                : peptide.labelColorHex,
          ),
        );
      }
    }
    return result;
  }

  void _moveWeek(int delta) {
    HapticFeedback.selectionClick();
    setState(() {
      _weekStart = _weekStart.add(Duration(days: 7 * delta));
      _selectedDate = _weekStart;
    });
  }

  void _jumpToToday() {
    HapticFeedback.selectionClick();
    final today = _day(DateTime.now());
    setState(() {
      _selectedDate = today;
      _weekStart = _mondayOf(today);
    });
  }
}

class _PlannerHeader extends StatelessWidget {
  const _PlannerHeader({
    required this.rangeLabel,
    required this.onBack,
    required this.onPrevious,
    required this.onNext,
  });

  final String rangeLabel;
  final VoidCallback onBack;
  final VoidCallback onPrevious;
  final VoidCallback onNext;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(
        AppSpacing.sm,
        AppSpacing.sm,
        AppSpacing.sm,
        0,
      ),
      child: Row(
        children: [
          IconButton(
            tooltip: 'Back',
            onPressed: onBack,
            icon: const Icon(
              Icons.arrow_back_rounded,
              color: AppColors.textPrimary,
            ),
          ),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('SYS.PROTOCOL // WEEK', style: AppTypography.systemLabel),
                const SizedBox(height: 2),
                Text(rangeLabel, style: AppTypography.h2),
              ],
            ),
          ),
          IconButton(
            tooltip: 'Previous week',
            onPressed: onPrevious,
            icon: const Icon(
              Icons.chevron_left_rounded,
              color: AppColors.textSecondary,
            ),
          ),
          IconButton(
            tooltip: 'Next week',
            onPressed: onNext,
            icon: const Icon(
              Icons.chevron_right_rounded,
              color: AppColors.textSecondary,
            ),
          ),
        ],
      ),
    );
  }
}

class _DayButton extends StatelessWidget {
  const _DayButton({
    required this.date,
    required this.doseCount,
    required this.selected,
    required this.isToday,
    required this.onTap,
  });

  final DateTime date;
  final int doseCount;
  final bool selected;
  final bool isToday;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return Semantics(
      button: true,
      selected: selected,
      label:
          '${_weekdayNames[date.weekday - 1]} ${date.day}, $doseCount scheduled ${doseCount == 1 ? 'dose' : 'doses'}',
      child: GestureDetector(
        onTap: onTap,
        child: AnimatedContainer(
          duration: AppDurations.fast,
          margin: const EdgeInsets.symmetric(horizontal: 2),
          padding: const EdgeInsets.symmetric(vertical: AppSpacing.sm),
          decoration: BoxDecoration(
            color: selected ? AppColors.primaryFaint : Colors.transparent,
            borderRadius: BorderRadius.circular(AppSpacing.buttonRadius),
            border: Border.all(
              color: selected
                  ? AppColors.primary
                  : isToday
                  ? AppColors.borderCyan
                  : AppColors.border,
            ),
          ),
          child: Column(
            children: [
              Text(
                _weekdayShort[date.weekday - 1],
                style: AppTypography.labelSmall.copyWith(
                  color: selected ? AppColors.primary : AppColors.textSecondary,
                  letterSpacing: 0.4,
                ),
              ),
              const SizedBox(height: AppSpacing.xs),
              Text(
                '${date.day}',
                style: AppTypography.tabular.copyWith(fontSize: 16),
              ),
              const SizedBox(height: AppSpacing.xs),
              Container(
                width: doseCount > 0 ? 6 : 3,
                height: doseCount > 0 ? 6 : 3,
                decoration: BoxDecoration(
                  color: doseCount > 0
                      ? AppColors.primary
                      : AppColors.textDisabled,
                  shape: BoxShape.circle,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _PlannedDoseCard extends StatelessWidget {
  const _PlannedDoseCard({required this.item});

  final _PlannerItem item;

  @override
  Widget build(BuildContext context) {
    final color = peptideLabelColor(item.colorHex);
    return AppCard(
      borderColor: color.withValues(alpha: 0.45),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          PeptideLabelAvatar(hex: item.colorHex),
          const SizedBox(width: AppSpacing.md),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Expanded(
                      child: Text(
                        item.peptide.peptideName,
                        style: AppTypography.labelLarge,
                      ),
                    ),
                    Text(
                      item.time,
                      style: AppTypography.tabular.copyWith(
                        color: color,
                        fontSize: 15,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: AppSpacing.xs),
                Text(
                  '${_amount(item.schedule.dosePerInjection)} ${item.schedule.doseUnit}${item.schedule.syringeUnits > 0 ? ' · ${_amount(item.schedule.syringeUnits)} units' : ''}',
                  style: AppTypography.bodyMedium.copyWith(
                    color: AppColors.textPrimary,
                  ),
                ),
                const SizedBox(height: AppSpacing.xs),
                Text(
                  item.protocol.name,
                  style: AppTypography.bodySmall.copyWith(
                    color: AppColors.textSecondary,
                  ),
                ),
                if (item.phase != null) ...[
                  const SizedBox(height: AppSpacing.sm),
                  _PhaseLabel(phase: item.phase!),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _PhaseLabel extends StatelessWidget {
  const _PhaseLabel({required this.phase});

  final ProtocolPhase phase;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(
        horizontal: AppSpacing.sm,
        vertical: AppSpacing.xs,
      ),
      decoration: BoxDecoration(
        color: AppColors.aiInsight.withValues(alpha: 0.22),
        borderRadius: BorderRadius.circular(6),
        border: Border.all(
          color: AppColors.aiInsightBright.withValues(alpha: 0.4),
        ),
      ),
      child: Text(
        'PHASE // ${phase.name.toUpperCase()}',
        style: AppTypography.systemLabel.copyWith(
          color: AppColors.aiInsightBright,
          fontSize: 9,
          letterSpacing: 1,
        ),
      ),
    );
  }
}

class _WashoutCard extends StatelessWidget {
  const _WashoutCard({required this.item});

  final _WashoutItem item;

  @override
  Widget build(BuildContext context) {
    final end = item.peptide.washoutEndDate(item.protocol.startDate);
    return AppCard(
      borderColor: AppColors.border,
      child: Row(
        children: [
          PeptideLabelAvatar(hex: item.colorHex, icon: Icons.pause_rounded),
          const SizedBox(width: AppSpacing.md),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(item.peptide.peptideName, style: AppTypography.labelLarge),
                const SizedBox(height: AppSpacing.xs),
                Text(
                  end == null
                      ? 'Washout period'
                      : 'Washout until ${_shortDate(end)}',
                  style: AppTypography.bodyMedium,
                ),
              ],
            ),
          ),
          Text(
            'WASHOUT',
            style: AppTypography.systemLabel.copyWith(
              color: AppColors.textSecondary,
              fontSize: 9,
            ),
          ),
        ],
      ),
    );
  }
}

class _EmptyDayCard extends StatelessWidget {
  const _EmptyDayCard();

  @override
  Widget build(BuildContext context) {
    return const AppCard(
      child: Row(
        children: [
          Icon(Icons.event_available_rounded, color: AppColors.textSecondary),
          SizedBox(width: AppSpacing.md),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('No scheduled doses', style: AppTypography.labelLarge),
                SizedBox(height: AppSpacing.xs),
                Text(
                  'Nothing is planned from your saved protocols.',
                  style: AppTypography.bodySmall,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _PlannerItem {
  const _PlannerItem({
    required this.protocol,
    required this.peptide,
    required this.schedule,
    required this.time,
    required this.phase,
    required this.colorHex,
  });

  final Protocol protocol;
  final ProtocolPeptide peptide;
  final ProtocolDoseSchedule schedule;
  final String time;
  final ProtocolPhase? phase;
  final String colorHex;
}

class _WashoutItem {
  const _WashoutItem({
    required this.protocol,
    required this.peptide,
    required this.colorHex,
  });

  final Protocol protocol;
  final ProtocolPeptide peptide;
  final String colorHex;
}

DateTime _day(DateTime value) => DateTime(value.year, value.month, value.day);

DateTime _mondayOf(DateTime value) =>
    _day(value).subtract(Duration(days: value.weekday - DateTime.monday));

bool _sameDay(DateTime a, DateTime b) =>
    a.year == b.year && a.month == b.month && a.day == b.day;

String _amount(double value) => value == value.roundToDouble()
    ? value.toInt().toString()
    : value
          .toStringAsFixed(2)
          .replaceFirst(RegExp(r'0+$'), '')
          .replaceFirst(RegExp(r'\.$'), '');

String _weekRangeLabel(DateTime monday) {
  final sunday = monday.add(const Duration(days: 6));
  if (monday.month == sunday.month) {
    return '${_months[monday.month - 1]} ${monday.day}–${sunday.day}';
  }
  return '${_months[monday.month - 1]} ${monday.day} – ${_months[sunday.month - 1]} ${sunday.day}';
}

String _fullDateLabel(DateTime date) =>
    '${_weekdayNames[date.weekday - 1]}, ${_months[date.month - 1]} ${date.day}';

String _shortDate(DateTime date) => '${_months[date.month - 1]} ${date.day}';

const _weekdayShort = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];
const _weekdayNames = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];
const _months = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];
